imports:
  root: ../__package__.yml
service:
  auth: false
  base-path: ''
  endpoints:
    get_default:
      path: /v1/voices/settings/default
      method: GET
      auth: false
      docs: >-
        Gets the default settings for voices. "similarity_boost" corresponds
        to"Clarity + Similarity Enhancement" in the web app and "stability"
        corresponds to "Stability" slider in the web app.
      source:
        openapi: openapi.json
      display-name: Get default voice settings
      response:
        docs: Successful Response
        type: root.VoiceSettings
        status-code: 200
      examples:
        - response:
            body:
              stability: 1
              use_speaker_boost: true
              similarity_boost: 1
              style: 0
              speed: 1
    get:
      path: /v1/voices/{voice_id}/settings
      method: GET
      auth: false
      docs: >-
        Returns the settings for a specific voice. "similarity_boost"
        corresponds to"Clarity + Similarity Enhancement" in the web app and
        "stability" corresponds to "Stability" slider in the web app.
      source:
        openapi: openapi.json
      path-parameters:
        voice_id:
          type: string
          docs: >-
            Voice ID to be used, you can use https://api.elevenlabs.io/v1/voices
            to list all the available voices.
      display-name: Get voice settings
      response:
        docs: Successful Response
        type: root.VoiceSettings
        status-code: 200
      errors:
        - root.UnprocessableEntityError
      examples:
        - path-parameters:
            voice_id: 21m00Tcm4TlvDq8ikWAM
          response:
            body:
              stability: 1
              use_speaker_boost: true
              similarity_boost: 1
              style: 0
              speed: 1
    update:
      path: /v1/voices/{voice_id}/settings/edit
      method: POST
      auth: false
      docs: >-
        Edit your settings for a specific voice. "similarity_boost" corresponds
        to "Clarity + Similarity Enhancement" in the web app and "stability"
        corresponds to "Stability" slider in the web app.
      source:
        openapi: openapi.json
      path-parameters:
        voice_id:
          type: string
          docs: >-
            ID of the voice to be used. You can use the [Get
            voices](/docs/api-reference/voices/search) endpoint list all the
            available voices.
      display-name: Edit voice settings
      request:
        body:
          type: root.VoiceSettings
          docs: The settings for a specific voice.
        content-type: application/json
      response:
        docs: Successful Response
        type: root.EditVoiceSettingsResponseModel
        status-code: 200
      errors:
        - root.UnprocessableEntityError
      examples:
        - path-parameters:
            voice_id: 21m00Tcm4TlvDq8ikWAM
          request:
            stability: 1
            use_speaker_boost: true
            similarity_boost: 1
            style: 0
            speed: 1
          response:
            body:
              status: ok
  source:
    openapi: openapi.json
